# Generated by Django 5.2.3 on 2026-02-11 09:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0024_alter_recipe_inventory_items_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('recipes_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('recipes_count', models.PositiveIntegerField(default=0)),
                ('labour_time', models.DurationField(blank=True, help_text='Format in POST: PT{hours}H{minutes}M or HH:MM:SS', null=True)),
                ('labour_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Rate per hour', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('labour_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total labour cost', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total cost of the product (recipes cost + labour cost)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductRecipes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recipes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recipes', to='products.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_products', to='recipes.recipe')),
            ],
            options={
                'ordering': ['product', 'recipe'],
                'unique_together': {('product', 'recipe', 'created_by')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='recipes',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', through='products.ProductRecipes', to='recipes.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'created_by')},
        ),
    ]
