# Generated by Django 5.2.3 on 2026-02-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrecipes',
            options={'ordering': ['product', 'recipe'], 'verbose_name': 'Product Recipe', 'verbose_name_plural': 'Product Recipes'},
        ),
    ]
