# Generated by Django 5.2.1 on 2025-07-10 16:02

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_alter_customer_email_alter_customertype_code'),
        ('recipes', '0006_alter_recipecategory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('order_no', models.CharField(max_length=10, null=True, unique=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_recipes', to='orders.order')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_recipes', to='recipes.recipe')),
            ],
            options={
                'unique_together': {('order', 'recipe')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='recipes',
            field=models.ManyToManyField(related_name='orders', through='orders.OrderRecipe', to='recipes.recipe'),
        ),
    ]
