# Generated by Django 5.2.3 on 2025-11-25 19:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_profit_percentage_alter_order_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrecipe',
            name='line_cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
