# Generated by Django 5.2.3 on 2026-01-19 19:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_overhead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='profit_percentage',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_value',
        ),
        migrations.RemoveField(
            model_name='orderrecipe',
            name='line_cost_price',
        ),
        migrations.RemoveField(
            model_name='orderrecipe',
            name='line_value',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_is_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Order price - discount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total cost + profit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='overhead',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='packaging',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_final_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='User-specified preferred final price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Profit margin percentage', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sum of all recipe costs', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='suggested_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Final price + VAT', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Subtotal + Overhead + Packaging', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('7.5'), help_text='VAT rate percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='orderrecipe',
            name='line_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Recipe total cost * quantity', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
