# Generated by Django 5.2.3 on 2026-01-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_overhead_name_alter_overhead_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='overhead_is_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='packaging_is_percentage',
            field=models.BooleanField(default=False),
        ),
    ]
