# Generated by Django 5.2.3 on 2026-02-27 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_contact'),
        ('orders', '0012_remove_order_recipes_alter_order_subtotal_and_more'),
        ('products', '0002_alter_productrecipes_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_by', 'status'], name='order_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_by', 'delivery_date'], name='order_user_delivery_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_by', '-created_at'], name='order_user_created_idx'),
        ),
    ]
