# Generated by Django 5.2.1 on 2025-06-06 15:25

from django.db import migrations

def create_customer_types(apps, schema_editor):
    CustomerType = apps.get_model("customers", "CustomerType")

    customer_types = [
        {
            "code": "retail",
            "name": "Retail Customer",
            "description": "Customers who purchase products for personal use.",
            "is_default": True,
        },
        {
            "code": "wholesale",
            "name": "Wholesale Customer",
            "description": "Businesses that buy in bulk for resale.",
            "is_default": True,
        },
        {
            "code": "corporate",
            "name": "Corporate Customer",
            "description": "Companies that purchase products for business purposes.",
            "is_default": True,
        },
        {
            "code": "vip",
            "name": "VIP Customer",
            "description": "High-value customers with frequent large orders, often eligible for special discounts.",
            "is_default": True,
        },
        {
            "code": "event",
            "name": "Event Customers",
            "description": "One-time customers who purchase products for specific events or occasions.",
            "is_default": True,
        },
        {
            "code": "promotional",
            "name": "Promotional Customer",
            "description": "Customers who engage with promotional campaigns or special offers.",
            "is_default": True,
        },
        {
            "code": "others",
            "name": "Others (Open Field)",
            "description": "To let users specify unique or less common goals.",
            "is_default": True,
        },
    ]

    for customer_type in customer_types:
        CustomerType.objects.get_or_create(**customer_type)

class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_customer_types, reverse_code=migrations.RunPython.noop),
    ]
