# Generated by Django 5.2.1 on 2025-06-17 08:47

from django.db import migrations


def create_customer_types(apps, schema_editor):
    CustomerType = apps.get_model("customers", "CustomerType")
    default_types = [
        {
            "code": "retail",
            "name": "Retail Customer",
            "description": "Individual customers buying for personal consumption",
            "is_default": True,
        },
        {
            "code": "wholesale",
            "name": "Wholesale Customer",
            "description": "Businesses buying in bulk for resale",
            "is_default": True,
        },
        {
            "code": "restaurant",
            "name": "Restaurant",
            "description": "Food service establishments requiring regular orders",
            "is_default": True,
        },
        {
            "code": "catering",
            "name": "Catering Service",
            "description": "Event planners and catering services",
            "is_default": True,
        },
        {
            "code": "corporate",
            "name": "Corporate Account",
            "description": "Business accounts for office orders and events",
            "is_default": True,
        },
        {
            "code": "other",
            "name": "Other",
            "description": "Enter a description",
            "is_default": True
        }
    ]

    for type_data in default_types:
        CustomerType.objects.create(**type_data)


def remove_customer_types(apps, schema_editor):
    CustomerType = apps.get_model("customers", "CustomerType")
    CustomerType.objects.filter(
        code__in=["retail", "wholesale", "restaurant", "catering", "corporate"]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(create_customer_types, remove_customer_types),
    ]
