# Generated by Django 5.2.3 on 2025-08-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_contact_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_type',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='custom_customer_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_discount_eligible',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='location_city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='location_country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='location_url',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='Jonathan', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='Mensah', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomerType',
        ),
    ]
