# Generated by Django 5.2.3 on 2026-01-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_remove_customer_customer_type_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
