# BASE - shared configuration
services:
  costmetrix:
    image: costmetrix
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c "python manage.py initialize_system &&
            python manage.py collectstatic --noinput &&
            watchfiles --filter python 'gunicorn config.wsgi:application --bind 0.0.0.0:8000' ./"
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped
    depends_on:
      - redis
      - db
  
  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    command: redis-server
    restart: unless-stopped

  celery_worker:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
      - db

  celery_beat:
    build: .
    command: sh -c "mkdir -p /app/beat && celery -A config beat -l info --schedule=/app/beat/celerybeat-schedule"
    volumes:
      - .:/app
      - celerybeat_schedule:/app/beat
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
  celerybeat_schedule:
