services:
  costmate:
    image: costmate
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c "python manage.py initialize_system &&
            python manage.py collectstatic --noinput &&
            watchfiles --filter python 'gunicorn config.wsgi:application --bind 0.0.0.0:8000' ./"
    volumes:
      - .:/app  # Sync local code for development
      - ./staticfiles:/app/staticfiles
    ports:
      - 8000:8000
    env_file:
      - .env  # Load all variables (DB_NAME, DB_USER, etc.) from here
    environment:
      - DB_HOST=host.docker.internal  # Changed from host.docker.internal to db
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped
    depends_on:
      - redis
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server
    restart: unless-stopped

volumes:
  redis_data:
