services:
  costnav: 
    command: >
      sh -c "python manage.py initialize_system &&
            python manage.py collectstatic --noinput &&
            gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./staticfiles:/app/staticfiles
  
  db:
    ports: []

  redis:
    ports: []
  
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles:ro
      - ./media_volume:/app/media_volume
      - /var/www/certbot:/var/lib/letsencrypt:ro
      - ./certbot-etc:/etc/letsencrypt:ro
    depends_on:
      - costnav
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - /var/www/certbot:/var/lib/letsencrypt
    entrypoint: /bin/sh
    command: -c "trap exit TERM; while :; do certbot renew --webroot -w /var/lib/letsencrypt --deploy-hook 'kill -HUP 1' --quiet; sleep 12h & wait $!; done"
  
volumes:
  media_volume: