services:
  - type: web
    name: costmate
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: costmate_db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.13.0

databases:
  - name: costmate
    plan: free
    databaseName: costmate_db