# Generated by Django 5.2.3 on 2025-11-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_subscription_plan_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('S', 'Starter'), ('P', 'Pro'), ('E', 'Enterprise')], default='starter', max_length=20),
        ),
    ]
