# Generated by Django 5.2.3 on 2025-11-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscription_tier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='end_date',
            new_name='current_sub_end',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='start_date',
            new_name='current_sub_start',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='customer_code',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('S', 'Starter'), ('P', 'Pro'), ('E', 'Enterprise')], default='S', max_length=20),
        ),
    ]
