# Generated by Django 5.2.3 on 2025-11-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_alter_subscription_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('S', 'Starter'), ('P', 'Pro'), ('E', 'Enterprise')], default='starter', max_length=20),
        ),
    ]
