# Generated by Django 5.2.3 on 2025-11-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_alter_subscription_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('S', 'Starter'), ('P', 'Pro'), ('E', 'Enterprise')], default='S', max_length=20),
        ),
    ]
