# Generated by Django 5.2.3 on 2025-12-06 10:08

import apps.subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0024_alter_subscription_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('S', 'Starter'), ('P', 'Pro'), ('E', 'Enterprise')], default=apps.subscriptions.models.get_default_subscription_tier, max_length=20),
        ),
    ]
