# Generated by Django 5.2.3 on 2026-01-15 08:34

import apps.subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0025_alter_subscription_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('UK_M', 'UK Monthly'), ('UK_Y', 'UK Yearly')], default=apps.subscriptions.models.get_default_subscription_tier, max_length=20),
        ),
    ]
