# Generated by Django 5.2.3 on 2026-01-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0026_alter_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
