# Generated by Django 5.2.1 on 2025-06-14 11:05

from django.db import migrations
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.contrib.auth.hashers import make_password


def create_initial_data(apps, schema_editor):
    User = apps.get_model("users", "User")
    InventoryItem = apps.get_model("inventory", "InventoryItem")
    Supplier = apps.get_model("inventory", "Supplier")

    # Get the superuser
    superuser = User.objects.filter(is_superuser=True).first()
    if not superuser:
        raise Exception("Superuser must exist before running this migration")

    # Create test users
    test_users = []
    for i in range(1, 6):
        user, _ = User.objects.get_or_create(
            email=f"test{i}@test.com",
            defaults={
                "first_name": "Test",
                "last_name": "User",
                "business_name": f"Test Business {i}",
                "location_country": "Test Country",
                "location_city": "Test City",
                "is_active": True,
                "password": make_password("Jonathan1@"),
            }
        )
        test_users.append(user)

    # Create default baking ingredients
    baking_ingredients = [
        {"name": "All-Purpose Flour", "unit": "kg"},
        {"name": "Granulated Sugar", "unit": "kg"},
        {"name": "Brown Sugar", "unit": "kg"},
        {"name": "Baking Powder", "unit": "g"},
        {"name": "Baking Soda", "unit": "g"},
        {"name": "Salt", "unit": "g"},
        {"name": "Butter", "unit": "kg"},
        {"name": "Eggs", "unit": "pcs"},
        {"name": "Milk", "unit": "l"},
        {"name": "Vanilla Extract", "unit": "ml"},
    ]

    # Create inventory items
    for item in baking_ingredients:
        InventoryItem.objects.get_or_create(
            name=item["name"],
            unit=item["unit"],
            created_by=superuser,
            defaults={"is_default": True},
        )

    # Create some suppliers
    suppliers = [
        "Baking Supply Co.",
        "Wholesale Ingredients Ltd.",
        "Fresh Products Inc.",
        "Quality Baking Supplies",
        "Organic Ingredients Co.",
    ]

    for supplier_name in suppliers:
        Supplier.objects.get_or_create(
            name=supplier_name,
            created_by=test_users[0],
            defaults={"contact": "1234567890"},
        )


def remove_initial_data(apps, schema_editor):
    User = apps.get_model("users", "User")
    InventoryItem = apps.get_model("inventory", "InventoryItem")
    Supplier = apps.get_model("inventory", "Supplier")

    User.objects.filter(email__contains="test").delete()
    InventoryItem.objects.filter(is_default=True).delete()
    Supplier.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_data, remove_initial_data),
    ]


