# Generated by Django 5.2.1 on 2025-06-14 11:05

from django.db import migrations
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.contrib.auth.hashers import make_password


def create_initial_data(apps, schema_editor):
    User = apps.get_model("users", "User")
    InventoryItem = apps.get_model("inventory", "InventoryItem")
    Supplier = apps.get_model("inventory", "Supplier")

    # Get the superuser
    superuser = User.objects.filter(is_superuser=True).first()
    if not superuser:
        raise Exception("Superuser must exist before running this migration")

    # Create test users
    test_users = []
    for i in range(1, 6):
        user = User.objects.create(
            email=f"test{i}@test.com",
            first_name="Test",
            last_name="User",
            business_name=f"Test Business {i}",
            location_country="Test Country",
            location_city="Test City",
            is_active=True,
            password=make_password("Jonathan1@")
        )
        user.save()
        test_users.append(user)

    # Create default baking ingredients
    baking_ingredients = [
        {"name": "All-Purpose Flour", "unit": "kg"},
        {"name": "Granulated Sugar", "unit": "kg"},
        {"name": "Brown Sugar", "unit": "kg"},
        {"name": "Baking Powder", "unit": "g"},
        {"name": "Baking Soda", "unit": "g"},
        {"name": "Salt", "unit": "g"},
        {"name": "Butter", "unit": "kg"},
        {"name": "Eggs", "unit": "pcs"},
        {"name": "Milk", "unit": "l"},
        {"name": "Vanilla Extract", "unit": "ml"},
    ]

    # Create inventory items
    for item in baking_ingredients:
        InventoryItem.objects.create(
            name=item["name"],
            unit=item["unit"],
            is_default=True,
            created_by=superuser,  # Super user creates default items
        )

    # Create some suppliers
    suppliers = [
        "Baking Supply Co.",
        "Wholesale Ingredients Ltd.",
        "Fresh Products Inc.",
        "Quality Baking Supplies",
        "Organic Ingredients Co.",
    ]

    for supplier_name in suppliers:
        Supplier.objects.create(
            name=supplier_name, contact="1234567890", created_by=test_users[0]
        )


def remove_initial_data(apps, schema_editor):
    User = apps.get_model("users", "User")
    InventoryItem = apps.get_model("inventory", "InventoryItem")
    Supplier = apps.get_model("inventory", "Supplier")

    User.objects.filter(email__contains="test").delete()
    InventoryItem.objects.filter(is_default=True).delete()
    Supplier.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_data, remove_initial_data),
    ]


