# Generated by Django 5.2.3 on 2025-08-02 13:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_load_dummy_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('currency', models.CharField(blank=True, default='GBP', max_length=10, null=True)),
                ('date_format', models.CharField(blank=True, default='DD/MM/YYYY', max_length=20, null=True)),
                ('language', models.CharField(blank=True, default='en', max_length=20, null=True)),
                ('time_zone', models.CharField(blank=True, default='UTC', max_length=10, null=True)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=Decimal('0.299999999999999988897769753748434595763683319091796875'), max_digits=3)),
                ('labor_rate', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5)),
                ('notification_preferences', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='primary_goal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='biggest_challenge',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='custom_business_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='custom_primary_goal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location_country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_currency',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_media_links',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.DeleteModel(
            name='BusinessType',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
