# Generated by Django 5.2.3 on 2025-08-05 12:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpreferences_remove_user_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.299999999999999988897769753748434595763683319091796875'), max_digits=4),
        ),
    ]
