# Generated by Django 5.2.3 on 2025-08-05 12:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userpreferences_profit_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.3'), max_digits=3),
        ),
    ]
