# Generated by Django 5.2.3 on 2025-08-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userpreferences_profit_margin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='id',
            new_name='user',
        ),
    ]
