# Generated by Django 5.2.3 on 2025-08-06 09:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_id_userpreferences_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Default profit margin as a percentage (e.g., 30.00 for 30%)', max_digits=3),
        ),
    ]
