# Generated by Django 5.2.3 on 2025-10-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userpreferences_profit_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='notification_preferences',
            field=models.JSONField(blank=True, default={'order_reminder': True, 'stock_alerts': True, 'weekly_reports': True}, null=True),
        ),
    ]
