# Generated by Django 5.2.3 on 2026-01-10 16:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='tax',
            field=models.BooleanField(default=False, help_text='Indicates whether tax should be applied to orders.'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax rate as a percentage (e.g., 20.00 for 20%)', max_digits=5),
        ),
    ]
