# Generated by Django 5.2.3 on 2026-01-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userpreferences_tax_userpreferences_tax_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='tax',
            new_name='tax_enabled',
        ),
    ]
