# Generated by Django 5.2.3 on 2026-01-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_tax_userpreferences_tax_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='estimated_monthly_orders',
            field=models.PositiveIntegerField(default=10, help_text='Estimated number of orders per month for subscription purposes.'),
        ),
    ]
