# Generated by Django 5.2.3 on 2026-01-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userpreferences_estimated_monthly_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_used_free_trial',
            field=models.BooleanField(default=False),
        ),
    ]
