# Generated by Django 5.2.3 on 2026-01-30 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_has_used_free_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingMetrics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='onboarding_metrics', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('has_entered_business_settings', models.BooleanField(default=False)),
                ('has_added_supplier', models.BooleanField(default=False)),
                ('has_added_inventory', models.BooleanField(default=False)),
                ('has_created_recipe', models.BooleanField(default=False)),
                ('has_calculated_overhead', models.BooleanField(default=False)),
                ('has_added_customer', models.BooleanField(default=False)),
                ('has_created_order', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Onboarding Metrics',
                'verbose_name_plural': 'Onboarding Metrics',
            },
        ),
    ]
