# Generated by Django 5.2.3 on 2026-02-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_add_onboarding_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingmetrics',
            name='has_created_product',
            field=models.BooleanField(default=False),
        ),
    ]
