# Generated by Django 5.2.3 on 2026-02-17 13:37

import apps.users.models
import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.logo_upload_path, validators=[apps.users.validators.validate_logo_file_size, apps.users.validators.validate_logo_file_extension, apps.users.validators.validate_logo_dimensions]),
        ),
    ]
