# Generated by Django 5.2.3 on 2026-02-19 15:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='deposit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deposit percentage required to confirm an order (e.g., 70.00 for 70%)', max_digits=5),
        ),
    ]
