# Generated by Django 5.2.3 on 2026-02-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_add_deposit_percentage_to_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='invoice_footer',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
