# Generated by Django 5.2.1 on 2025-06-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterModelOptions(
            name='inventoryhistory',
            options={'verbose_name_plural': 'Inventory History'},
        ),
    ]
