# Generated by Django 5.2.1 on 2025-06-14 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_inventories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_inventory_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_inventory_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_suppliers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('name', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('inventory_item', 'created_by')},
        ),
    ]
