# Generated by Django 5.2.1 on 2025-06-13 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
