# Generated by Django 5.2.3 on 2025-06-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryhistory',
            old_name='purchase_date',
            new_name='incident_date',
        ),
    ]
