# Generated by Django 5.2.1 on 2025-06-19 09:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_purchase_date_inventoryhistory_incident_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhistory',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
