# Generated by Django 5.2.1 on 2025-06-13 19:10

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Inventory = apps.get_model("inventory", "Inventory")
    for row in Inventory.objects.all():
        row.id = uuid.uuid4()
        row.save(update_fields=["id"])

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_id'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
