# Generated by Django 5.2.1 on 2025-06-13 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20250613_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
