# Generated by Django 5.2.1 on 2025-07-06 14:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryhistory_cost_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
