# Generated by Django 5.2.3 on 2025-08-06 09:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_cost_per_unit_inventory_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
