# Generated by Django 5.2.1 on 2025-06-13 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_auto_20250613_1910"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="inventory_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
