# Generated by Django 5.2.3 on 2025-10-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventoryhistory_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
