# Generated by Django 5.2.1 on 2025-06-13 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventory_id_alter_inventory_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.inventoryitem'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('name', 'created_by')},
        ),
    ]
