# Generated by Django 5.2.3 on 2025-11-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_supplier_contact_alter_supplier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='days_of_stock_on_hand',
            field=models.IntegerField(default=0),
        ),
    ]
