# Generated by Django 5.2.3 on 2025-12-05 15:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_supplier_address_supplier_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
    ]
