# Generated by Django 5.2.3 on 2025-12-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventoryitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
