# Generated by Django 5.2.3 on 2025-12-24 09:17

from django.db import migrations

def populate_inventory_units(apps, schema_editor):
    InventoryUnit = apps.get_model('inventory', 'InventoryUnit')
    User = apps.get_model('users', 'User')
    superuser = User.objects.filter(is_superuser=True).first()
    if not superuser:
        raise Exception("Superuser must exist before running this migration")

    default_units = [
        {"name": "Gram", "unit_symbol": "g"},
        {"name": "Kilogram", "unit_symbol": "kg"},
        {"name": "Ounce", "unit_symbol": "oz"},
        {"name": "Pound", "unit_symbol": "lb"},
        {"name": "Millilitre", "unit_symbol": "ml"},
        {"name": "Litre", "unit_symbol": "L"},
        {"name": "Fluid Ounce", "unit_symbol": "fl oz"},
        {"name": "Cup", "unit_symbol": "cup"},
        {"name": "Teaspoon", "unit_symbol": "tsp"},
        {"name": "Tablespoon", "unit_symbol": "tbsp"},
        {"name": "Pint", "unit_symbol": "pt"},
        {"name": "Quart", "unit_symbol": "qt"},
        {"name": "Gallon", "unit_symbol": "gal"},
        {"name": "Pieces", "unit_symbol": "pcs"},
        {"name": "Bottle", "unit_symbol": "bottle"},
        {"name": "Can", "unit_symbol": "can"},
        {"name": "Jar", "unit_symbol": "jar"},
        {"name": "Bag", "unit_symbol": "bag"},
        
    ]

    for unit in default_units:
        InventoryUnit.objects.create(
            name=unit["name"],
            unit_symbol=unit["unit_symbol"],
            is_default=True,
            created_by=superuser,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_inventoryunit'),
    ]

    operations = [
        migrations.RunPython(populate_inventory_units),
    ]
