# Generated by Django 5.2.3 on 2026-01-06 21:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_preload_inventory_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='total_value',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
