# Generated by Django 5.2.3 on 2026-02-27 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_inventory_cost_per_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventoryhistory',
            index=models.Index(fields=['inventory_item', '-incident_date'], name='invhistory_item_date_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryhistory',
            index=models.Index(fields=['created_by', '-incident_date'], name='invhistory_user_date_idx'),
        ),
    ]
