# Generated by Django 5.2.1 on 2025-06-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeinventory',
            options={'verbose_name_plural': 'Recipe Inventory'},
        ),
    ]
