# Generated by Django 5.2.1 on 2025-06-12 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeinventory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
