# Generated by Django 5.2.3 on 2025-06-24 09:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_total_cost_recipeinventory_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='total_cost',
            new_name='inventory_items_cost',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Calculated cost price', max_digits=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions for preparing the recipe', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='Indicates if the recipe is a draft'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='labour_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total labour cost', max_digits=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='labour_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Rate per hour', max_digits=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='overhead_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Overhead cost per unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='packaging_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cost of packaging per unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Margin percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='recipe',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Calculated selling price', max_digits=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.recipecategory'),
        ),
    ]
