# Generated by Django 5.2.3 on 2025-06-25 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipecategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecategory',
            name='created_by',
            field=models.ForeignKey(default='216355dd-a83b-416b-9e94-0be1612b0cdd', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_categories', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
