# Generated by Django 5.2.1 on 2025-07-06 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipecategory_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'verbose_name_plural': 'Recipe Categories'},
        ),
    ]
