# Generated by Django 5.2.3 on 2025-08-06 09:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipecategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeinventory',
            name='cost',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Calculated cost price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='inventory_items_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='labour_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total labour cost', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='labour_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Rate per hour', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='overhead_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Overhead cost per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='packaging_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cost of packaging per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Margin percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Calculated selling price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
