# Generated by Django 5.2.3 on 2025-08-06 11:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipeinventory_cost_alter_recipe_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeinventory',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
