# Generated by Django 5.2.3 on 2025-08-08 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventoryhistory_cost_per_unit_and_more'),
        ('recipes', '0008_recipeinventory_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.recipecategory'),
        ),
        migrations.AlterField(
            model_name='recipeinventory',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_inventory', to='inventory.inventoryitem'),
        ),
    ]
