# Generated by Django 5.2.3 on 2025-10-05 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_is_public_recipe_share_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinventory',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
