# Generated by Django 5.2.3 on 2025-10-20 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipeinventory_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Recipe Categories'},
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='recipecategory',
            unique_together={('name', 'created_by')},
        ),
    ]
