# Generated by Django 5.2.3 on 2025-11-11 17:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_recipeinventory_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Calculated cost price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='inventory_items_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Calculated selling price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
