# Generated by Django 5.2.3 on 2025-11-11 17:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_recipe_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinventory',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
