# Generated by Django 5.2.3 on 2025-11-11 17:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_recipeinventory_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinventory',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
