# Generated by Django 5.2.3 on 2025-12-18 14:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_alter_recipe_inventory_items_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeinventory',
            name='suggested_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Suggested cost if not available from inventory', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
