# Generated by Django 5.2.3 on 2026-01-06 21:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_recipeinventory_suggested_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cost_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Calculated cost price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='inventory_items_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='selling_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Calculated selling price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipeinventory',
            name='cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipeinventory',
            name='suggested_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Suggested cost if not available from inventory', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
