# Generated by Django 5.2.3 on 2026-01-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_alter_recipe_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Indicates if the recipe is a draft'),
        ),
    ]
