# Generated by Django 5.2.3 on 2026-01-19 17:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_recipe_is_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='category',
            new_name='recipe_category',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='overhead_cost',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='packaging_cost',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='profit_margin',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Total cost (inventory_items_cost + labour_cost)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='inventory_items_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Total cost of inventory items', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
