# Generated by Django 5.2.3 on 2026-01-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_rename_category_recipe_recipe_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_category',
            new_name='category',
        ),
    ]
