# Generated by Django 5.2.3 on 2026-01-19 19:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_rename_recipe_category_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='inventory_items_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total cost of inventory items', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total cost (inventory_items_cost + labour_cost)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipeinventory',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipeinventory',
            name='suggested_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Suggested cost if not available from inventory', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
