# Generated by Django 5.2.3 on 2026-02-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_alter_recipe_inventory_items_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecategory',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
