# Generated by Django 5.2.3 on 2026-03-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_recipestep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipestep',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
