# Generated by Django 5.2.3 on 2025-10-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notificatio_user_id_8a7c6b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REORDER_CHECK', 'Reorder level check'), ('DELIVERY_REMINDER', 'Delivery reminder'), ('WEEKLY_REPORTS', 'Weekly reports')], max_length=50),
        ),
    ]
