# Generated by Django 5.2.3 on 2026-01-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REORDER_CHECK', 'Reorder level check'), ('DELIVERY_REMINDER', 'Delivery reminder'), ('WEEKLY_REPORTS', 'Weekly reports'), ('INSUFFICIENT_INVENTORY', 'Insufficient inventory for order')], max_length=50),
        ),
    ]
