# Generated by Django 5.2.3 on 2026-01-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REORDER_CHECK', 'Reorder level check'), ('DELIVERY_REMINDER', 'Delivery reminder'), ('WEEKLY_REPORTS', 'Weekly reports'), ('INSUFFICIENT_INVENTORY', 'Insufficient inventory for order'), ('TRIAL_ENDING', 'Trial period ending soon')], max_length=50),
        ),
    ]
